set_family {SmartFusion2}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\CoreConfigP\7.1.100\rtl\vlog\core\coreconfigp.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\CoreResetP\7.1.100\rtl\vlog\core\coreresetp_pcie_hotreset.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\CoreResetP\7.1.100\rtl\vlog\core\coreresetp.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\MSS_SUBSYSTEM_sb\CCC_0\MSS_SUBSYSTEM_sb_CCC_0_FCCC.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\MSS_SUBSYSTEM_sb\FABOSC_0\MSS_SUBSYSTEM_sb_FABOSC_0_OSC.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\MSS_SUBSYSTEM_sb_MSS\MSS_SUBSYSTEM_sb_MSS.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\MSS_SUBSYSTEM_sb\MSS_SUBSYSTEM_sb.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\CoreGPIO_IN\rtl\vlog\core\coregpio.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\CoreGPIO_OUT\rtl\vlog\core\coregpio.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\CoreUARTapb_0\rtl\vlog\core\Clock_gen.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\CoreUARTapb_0\rtl\vlog\core\Rx_async.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\CoreUARTapb_0\rtl\vlog\core\Tx_async.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\CoreUARTapb_0\rtl\vlog\core\fifo_256x8_g4.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\CoreUARTapb_0\rtl\vlog\core\CoreUART.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\CoreUARTapb_0\rtl\vlog\core\CoreUARTapb.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\CoreAHBLite\5.3.101\rtl\vlog\core\coreahblite_addrdec.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\CoreAHBLite\5.3.101\rtl\vlog\core\coreahblite_defaultslavesm.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\CoreAHBLite\5.3.101\rtl\vlog\core\coreahblite_masterstage.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\CoreAHBLite\5.3.101\rtl\vlog\core\coreahblite_slavearbiter.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\CoreAHBLite\5.3.101\rtl\vlog\core\coreahblite_slavestage.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\CoreAHBLite\5.3.101\rtl\vlog\core\coreahblite_matrix4x16.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\CoreAHBLite_0\rtl\vlog\core\coreahblite.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\CoreAHBLite_1\rtl\vlog\core\coreahblite.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_ahbtoapbsm.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_apbaddrdata.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_penablescheduler.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3.v}
read_verilog -mode verilog_2k -lib COREAPB3_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core\coreapb3_muxptob3.v}
read_verilog -mode verilog_2k -lib COREAPB3_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core\coreapb3_iaddr_reg.v}
read_verilog -mode verilog_2k -lib COREAPB3_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core\coreapb3.v}
read_verilog -mode verilog_2k -lib COREJTAGDEBUG_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\COREJTAGDEBUG\3.0.100\core\corejtagdebug_ujtag_wrapper.v}
read_verilog -mode verilog_2k -lib COREJTAGDEBUG_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\COREJTAGDEBUG\3.0.100\core\corejtagdebug_uj_jtag.v}
read_verilog -mode verilog_2k -lib COREJTAGDEBUG_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\COREJTAGDEBUG\3.0.100\core\corejtagdebug.v}
read_verilog -mode verilog_2k -lib CORETIMER_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\Actel\DirectCore\CoreTimer\2.0.103\rtl\vlog\core\coretimer.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_coreplex_local_interrupter_clint.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_capture_chain.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_capture_update_chain.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_capture_update_chain_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_jtag_bypass_chain.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_capture_update_chain_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg_vec_90.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_jtag_state_machine.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_negative_edge_latch.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_negative_edge_latch_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_jtag_tap_controller.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_debug_transport_module_jtag.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xbar.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xbar_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xbar_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xing.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg_vec_89.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_reset_catch_and_sync.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xbar_int_xbar.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xing_xing.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_amoalu.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_arbiter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_arbiter_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_d_cache_data_array.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_pmp_checker.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tlb.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_d_cache_dcache.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_i_cache_icache.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_shift_queue.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tlb_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_frontend_frontend.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_hella_cache_arbiter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_rr_arbiter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_ptw.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_alu.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_breakpoint_unit.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_csr_file.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_rvc_expander.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_i_buf.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_mul_div.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_rocket.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_tile_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_rocket_tile_rocket.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_sync_rocket_tile_tile.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tlfifo_fixer_system_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_level_gateway.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_13.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tlplic_plic.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_atomic_automata.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_4.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_5.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_6.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_7.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_8.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_10.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_9.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_3.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_4.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_23.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_24.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_25.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_26.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_27.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_error.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_14.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_15.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_16.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_17.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_18.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_system_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_cache_cork.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg_vec_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_3.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_4.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_5.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_sink_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_sink_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_source_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_async_crossing_sink.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_inner_dm_inner.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_inner_async_dm_inner.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_source_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_dmi_to_tl_dmi2tl.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_sink.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_source.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_async_crossing_source_dm_inner.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg_vec.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_outer_dm_outer.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_dmi_xbar.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_outer_async_dm_outer.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_debug.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_21.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_22.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_error_error.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_filter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_repeater.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_repeater_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_fragmenter_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_splitter_system_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_20.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_to_ahb.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_19.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_to_ahb_converter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_width_widget.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_width_widget_3.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_memory_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_periphery_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_system_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb_core_risc_vahb_top.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\MIV_RV32IMA_L1_AHB_0\rtl\vlog\core\miv_rv32ima_l1_ahb.v}
read_verilog -mode verilog_2k {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\component\work\PROC_SUBSYSTEM\PROC_SUBSYSTEM.v}
set_top_level {PROC_SUBSYSTEM}
map_netlist
read_sdc {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\constraint\PROC_SUBSYSTEM_derived_constraints.sdc}
read_sdc {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\constraint\user.sdc}
check_constraints {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\constraint\synthesis_sdc_errors.log}
write_fdc {C:\Users\ciaran.lappin\Downloads\M2S025-Creative-Board-master\Modify_The_FPGA_Design\MIV_RV32IMA_L1_AHB_BaseDesign\designer\PROC_SUBSYSTEM\synthesis.fdc}
